//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Xylia.Match.Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Xylia.Match.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;table&gt;
        ///	&lt;record type=&quot;critical&quot; k=&quot;97&quot; μ=&quot;&quot; Φ=&quot;&quot; &gt;
        ///		&lt;level key=&quot;60&quot; value=&quot;7937.55&quot; /&gt;
        ///	&lt;/record&gt;
        ///	&lt;record type=&quot;attribute&quot; c=&quot;100&quot; k=&quot;291&quot; μ=&quot;&quot; Φ=&quot;&quot; &gt;
        ///		&lt;level key=&quot;60&quot; value=&quot;12002.79&quot; /&gt;
        ///	&lt;/record&gt;
        ///	&lt;record type=&quot;critical-damage&quot; c=&quot;125&quot; k=&quot;291&quot; &gt;
        ///		&lt;level key=&quot;60&quot; value=&quot;7201.28&quot; /&gt;
        ///	&lt;/record&gt;
        ///	&lt;record type=&quot;abnormal-attack&quot; c=&quot;100&quot; k=&quot;291&quot; &gt;
        ///		&lt;level key=&quot;60&quot; value=&quot;12744.27&quot; /&gt;
        ///	&lt;/record&gt;
        ///	&lt;record type=&quot;hit&quot; c=&quot;85&quot; k=&quot;96&quot; &gt;
        ///		&lt;level key=&quot;60&quot; valu [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        public static string Attribute {
            get {
                return ResourceManager.GetString("Attribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;Game&gt;
        ///	&lt;!-- 手动添加名称缺失道具 --&gt;
        ///	&lt;record alias=&quot;Test_N-ShopAccountShippingItem&quot; name2=&quot;N-Shop帐号配送物品&quot; /&gt;
        ///	&lt;record alias=&quot;Test_N-ShopCharacterShippingItem&quot; name2=&quot;N-Shop角色配送物品&quot; /&gt;
        ///	&lt;record alias=&quot;BabaB2_0146&quot; name2=&quot;哈迪斯&quot; /&gt;
        ///	&lt;record alias=&quot;BabaC_0147&quot; name2=&quot;哈迪斯&quot; /&gt;
        ///	&lt;record alias=&quot;InsectTribeGrasshopperA_0148&quot; name2=&quot;哈迪斯&quot; /&gt;
        ///	&lt;record alias=&quot;InsectTribeGrasshopperB_0149&quot; name2=&quot;哈迪斯&quot; /&gt;
        ///	&lt;record alias=&quot;Flazard_0150&quot; name2=&quot;哈迪斯&quot; /&gt;
        ///	&lt;record alias=&quot;DoubleAxe_0151&quot; na [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        public static string Game {
            get {
                return ResourceManager.GetString("Game", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap Panel_BackGround {
            get {
                object obj = ResourceManager.GetObject("Panel_BackGround", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;table release-module=&quot;LocalData&quot; release-side=&quot;client&quot; type=&quot;tips&quot; version=&quot;1.2&quot;&gt;
        ///  &lt;!-- 这是用于MainPage的提示文本 --&gt;
        ///  &lt;record text=&quot;按住Ctrl并滚动鼠标滚轮, 可以放缩输出信息框&quot;/&gt;
        ///  &lt;record text=&quot;小知识：任务名称为红色代表无法执行&quot;/&gt; 
        ///  &lt;record text=&quot;小知识：自身等级大于推荐等级10级时, 任务将显示为灰色&quot;/&gt;
        ///  &lt;record text=&quot;小知识：自身等级大于推荐等级20级时, 任务将变为低等级任务&quot;/&gt; 
        ///
        ///  &lt;!-- prop 模块 --&gt;
        ///  &lt;record module=&quot;prop&quot; text=&quot;在物品预览中，首次查询将会建立内存数据, 耗时约需半分钟。此后会极大加速。&quot; proweight=&quot;100&quot; /&gt;
        ///  &lt;record module=&quot;prop&quot; text=&quot;在物品预览中，双击物品名称可复制物品信息&quot; /&gt;
        ///  &lt;rec [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        public static string Tips {
            get {
                return ResourceManager.GetString("Tips", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap Update24 {
            get {
                object obj = ResourceManager.GetObject("Update24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap Update24_Orange {
            get {
                object obj = ResourceManager.GetObject("Update24_Orange", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap Update24_Pink {
            get {
                object obj = ResourceManager.GetObject("Update24_Pink", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
